apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: board-generator
data:
  zap-logger-config.yaml: |
    level: info
    development: false
    outputPaths: ["stdout"]
    errorOutputPaths: ["stderr"]
    encoding: console
    encoderConfig:
      timeKey: ts
      levelKey: level
      nameKey: logger
      callerKey: caller
      messageKey: msg
      stacktraceKey: stacktrace
      lineEnding: ""
      levelEncoder: "capitalColor"
      timeEncoder: iso8601
      durationEncoder: ""
      callerEncoder: ""
